apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
spec:
  selector:
    app: mqtt
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP
