apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    pid_file /var/run/mosquitto/mosquitto.pid
    user mosquitto
    allow_anonymous true
    listener 1883
    listener 9001
    protocol websockets
